
= _Debian_ basic installation with _Gnome_
☣ By Alejandro Martin
:docinfo: shared
:toc: left
:icons: font
:last-update-label!:
:linkattrs:

* The used release is _Debian Buster_.
* Sources and issues reports on https://github.com/alejandro-martin/debian-installation[Github, window="_blank"]

Guide for a basic _Debian_ installation with _Gnome_ desktop.

NOTE: All the commands have to be run as superuser.

<<<

== Minimal system installation

. Create bootable USB. If extra firmware(drivers) are needed,
 download them from _Debian_ repositories website and put _.ucode_ and _.fw_ files
 in the root of another USB.
. Boot system from USB. If _UEFI_ installation is needed, boot the USB in
UEFI mode, and after keyboard configuration go to a new terminal(`ctrl+alt+f2`)
 and type:
+
 [ -d /sys/firmware/efi ] && echo UEFI || echo Legacy
+
which it is going to print if the system was booted in _UEFI_ or _Legacy_ mode.
Return to installation with (`ctrl+alt+f1`).
+
. Follow the installation steps and at section _Software Selection_,
*ONLY* tick *_Standard System Utilities_*
for a minimal system installation.
. Reboot the system and remove usb.

== Connect to a wireless network [Optional]

. Login as superuser:

 su

. Look for the interface that it is going to be used. Wifi interface it may have a
name like `wlan0` or `wlp1s0`:

 ip a

. Turn on interface:

 ip link set INTERFACE_NAME up

. Look for a network to connect (replace interface name):

 iw INTERFACE_NAME scan | less

. Create a file with the network(replacing `NETWORK_NAME`). NOTE: After run
the command, the password has to be inmediately typed:

 wpa_passphrase NETWORK_NAME >> /etc/wpa_supplicant/wpa_supplicant.conf

. Init the connection, using `-B` flag to run on background:

 wpa_supplicant -B -i INTERFACE_NAME -c /etc/wpa_supplicant/wpa_supplicant.conf

. Get an ip address using _dhcp_ client:

 dhclient INTERFACE_NAME

. Test connection(ping to Google dns):

 ping 8.8.8.8

. In case is needed, to release ip type:

 dhclient -r

. Optionally, to turn off the interface:

 ip link set INTERFACE_NAME down

== Configure repositories

. Enter as superuser:

 su

. Edit repositories file (the editor *_nano_* is used this time):

 nano /etc/apt/sources.list

. Comment the line(add `#` at the beginning of line) if it starts with `deb cdrom`.

. Add `contrib` and `non-free` packages, appending `contrib non-free`
after `main` in each repository line

. Adjust mirror repository on each url base on your location ,
look for it at the _Debian_ https://www.debian.org/mirror/list[_Mirrors_ website, window="_blank"].

. [Optional] Add testing repositories replacing `stable` for `testing` on each line.
+
IMPORTANT: This step is only needed if the _Debian Testing_ release is wanted.

. Save and quit.

. It may end up like this(replace `MIRROR` with you region):
+
.sources.list
----
 deb http://ftp.MIRROR.debian.org/debian/ testing main contrib non-free
 deb-src http://ftp.MIRROR.debian.org/debian/ testing main contrib non-free

 deb http://security.debian.org/ testing/updates main contrib non-free
 deb-src http://security.debian.org/ testing/updates main contrib non-free

 deb http://ftp.MIRROR.debian.org/debian/ testing-updates main contrib non-free
 deb-src http://ftp.MIRROR.debian.org/debian/ testing-updates main contrib non-free
----
+
NOTE: This is for a _Debian Testing_, the word `testing` could be replaced with
`stable` or `unstable`. For more information go to
https://www.debian.org/releases/[_Debian Releases_ website, window="_blank"].

+
. [Optional] If you keep stable version and you want newer packages
(from testing distribution, mostly) you could append the _backports_ repositories.
+
.sources.list[fragment]
----

# ... previous sources ...

# backports
deb http://ftp.MIRROR.debian.org/debian/ stretch-backports main contrib non-free
deb-src http://ftp.MIRROR.debian.org/debian/ stretch-backports main contrib non-free
----
+
Important, to install any package from the backports, it has to be installed with:

 apt-get -t stretch-backports install "package"
+

NOTE: These are the _backports_ repositories for the actual "Stretch" stable release.
For more information look for the official
https://backports.debian.org/Instructions/[_backports instructions_, window="_blank"].

== Update & Upgrade

. Update packages:

 apt-get update

. Upgrade packages:

 apt-get upgrade

. If testing repositories were added, it will need a _dist-upgrade_:

 apt-get dist-upgrade

== Add superuser privileges to main user

. Install `sudo` package

 apt-get install sudo

. Add user to group `sudo`(this one is already configured in `/etc/sudoers`
  with the permissions, replace USERNAME):
+
 adduser USERNAME sudo
+
As an alternative it can be used:
+
 usermod -a -G sudo USERNAME


== Install firmware

. Install all linux firmware

 apt-get install firmware-linux firmware-linux-free firmware-linux-nonfree

. Install wifi firmware:
+
 apt-get install firmware-iwlwifi
+
As an alternative, to install wifi in older _Debian_ versions:
+
 apt-get install iwlwifi

== Install minimal _Gnome_ desktop

. Install display server(`xserver-xorg-core`), minimal gnome desktop(`gnome-core`)
  and gnome display manager(`gdm3`):
+
 apt-get install xserver-xorg-core gnome-core gdm3
+
In older _Debian_ versions it can be used:
+
 apt-get install xorg gnome-core gdm3

== Install Graphics card firmware

=== Install _Nvidia_ Drivers

. Install _Nvidia_ firmware:
+
 apt-get install linux-headers-$(uname -r|sed 's/[^-]*-[^-]*-//') nvidia-driver
+
For support of _GeForce_ 6xxx and 7xxx GPUs:
+
 apt-get install linux-headers-$(uname -r|sed 's/[^-]*-[^-]*-//') nvidia-legacy-340xx-driver

NOTE: Usually propietary drivers for Gpus have better performance. They can be downloaded
from their own websites.

=== Install _AMD_ Graphics Drivers

. Install _AMD_ graphics firmware:

 apt-get install linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,') fglrx-driver

== Reboot

. Reboot system:

 reboot

IMPORTANT: After installation it should verify that _Debian_ partition is
the primary boot drive in order to run the grub for multi-booting systems.

== On _Debian_ installation series

* link:./index-02.html[02 - Debian Post Installation]
* link:./index-03.html[03 - Debian Developer Installation]
* link:./index-04.html[04 - Debian Gnome Configuration]

include::disqus.adoc[]
